# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('path', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=240)),
            ],
        ),
        migrations.AddField(
            model_name='basefile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spending.User'),
        ),
    ]
